package com.yunda.gps.vehicleRecord.mapper;

import java.util.List;
import java.util.Map;

import com.yunda.gps.vehicleRecord.bean.VehicleRecord;

public interface VehicleRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String vehicleId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_record
     *
     * @mbggenerated
     */
    int insertSelective(VehicleRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_record
     *
     * @mbggenerated
     */
    VehicleRecord selectByPrimaryKey(String vehicleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VehicleRecord record);
    /**
     * 根据表名查询最大表
     * @param record
     * @return
     */
    Map<String,String> selectMaxTableName(VehicleRecord record);
    /**
     * 根据表名查询记录数
     * @param record
     * @return
     */
    int selectCount(VehicleRecord record);
    
    /**
     * 分页查询车辆安装维护
     * @param vehicleRecord
     * @return
     */
    public List<VehicleRecord> pageQuery(VehicleRecord vehicleRecord);
    
}