package com.yunda.inter.outsideInterface.bean;


public class SynVehicle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syn_vehicle.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syn_vehicle.LICENSECARD
     *
     * @mbggenerated
     */
    private String licensecard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syn_vehicle.VEHICLE_ID
     *
     * @mbggenerated
     */
    private String vehicleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syn_vehicle.VEHICLE_TYPE
     *
     * @mbggenerated
     */
    private String vehicleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syn_vehicle.VEHICLE_PROPERTIES
     *
     * @mbggenerated
     */
    private String vehicleProperties;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syn_vehicle.CARRIER_CODE
     *
     * @mbggenerated
     */
    private String carrierCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syn_vehicle.TRANSPORT_COMPANY
     *
     * @mbggenerated
     */
    private String transportCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syn_vehicle.CREATE_TIME
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syn_vehicle.CREATE_BY
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syn_vehicle.UPDATE_TIME
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syn_vehicle.UPDATE_BY
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syn_vehicle.DELETE_FLAG
     *
     * @mbggenerated
     */
    private Byte deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syn_vehicle.ID
     *
     * @return the value of syn_vehicle.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syn_vehicle.ID
     *
     * @param id the value for syn_vehicle.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syn_vehicle.LICENSECARD
     *
     * @return the value of syn_vehicle.LICENSECARD
     *
     * @mbggenerated
     */
    public String getLicensecard() {
        return licensecard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syn_vehicle.LICENSECARD
     *
     * @param licensecard the value for syn_vehicle.LICENSECARD
     *
     * @mbggenerated
     */
    public void setLicensecard(String licensecard) {
        this.licensecard = licensecard == null ? null : licensecard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syn_vehicle.VEHICLE_ID
     *
     * @return the value of syn_vehicle.VEHICLE_ID
     *
     * @mbggenerated
     */
    public String getVehicleId() {
        return vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syn_vehicle.VEHICLE_ID
     *
     * @param vehicleId the value for syn_vehicle.VEHICLE_ID
     *
     * @mbggenerated
     */
    public void setVehicleId(String vehicleId) {
        this.vehicleId = vehicleId == null ? null : vehicleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syn_vehicle.VEHICLE_TYPE
     *
     * @return the value of syn_vehicle.VEHICLE_TYPE
     *
     * @mbggenerated
     */
    public String getVehicleType() {
        return vehicleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syn_vehicle.VEHICLE_TYPE
     *
     * @param vehicleType the value for syn_vehicle.VEHICLE_TYPE
     *
     * @mbggenerated
     */
    public void setVehicleType(String vehicleType) {
        this.vehicleType = vehicleType == null ? null : vehicleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syn_vehicle.VEHICLE_PROPERTIES
     *
     * @return the value of syn_vehicle.VEHICLE_PROPERTIES
     *
     * @mbggenerated
     */
    public String getVehicleProperties() {
        return vehicleProperties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syn_vehicle.VEHICLE_PROPERTIES
     *
     * @param vehicleProperties the value for syn_vehicle.VEHICLE_PROPERTIES
     *
     * @mbggenerated
     */
    public void setVehicleProperties(String vehicleProperties) {
        this.vehicleProperties = vehicleProperties == null ? null : vehicleProperties.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syn_vehicle.CARRIER_CODE
     *
     * @return the value of syn_vehicle.CARRIER_CODE
     *
     * @mbggenerated
     */
    public String getCarrierCode() {
        return carrierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syn_vehicle.CARRIER_CODE
     *
     * @param carrierCode the value for syn_vehicle.CARRIER_CODE
     *
     * @mbggenerated
     */
    public void setCarrierCode(String carrierCode) {
        this.carrierCode = carrierCode == null ? null : carrierCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syn_vehicle.TRANSPORT_COMPANY
     *
     * @return the value of syn_vehicle.TRANSPORT_COMPANY
     *
     * @mbggenerated
     */
    public String getTransportCompany() {
        return transportCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syn_vehicle.TRANSPORT_COMPANY
     *
     * @param transportCompany the value for syn_vehicle.TRANSPORT_COMPANY
     *
     * @mbggenerated
     */
    public void setTransportCompany(String transportCompany) {
        this.transportCompany = transportCompany == null ? null : transportCompany.trim();
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syn_vehicle.CREATE_BY
     *
     * @return the value of syn_vehicle.CREATE_BY
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syn_vehicle.CREATE_BY
     *
     * @param createBy the value for syn_vehicle.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syn_vehicle.UPDATE_BY
     *
     * @return the value of syn_vehicle.UPDATE_BY
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syn_vehicle.UPDATE_BY
     *
     * @param updateBy the value for syn_vehicle.UPDATE_BY
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syn_vehicle.DELETE_FLAG
     *
     * @return the value of syn_vehicle.DELETE_FLAG
     *
     * @mbggenerated
     */
    public Byte getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syn_vehicle.DELETE_FLAG
     *
     * @param deleteFlag the value for syn_vehicle.DELETE_FLAG
     *
     * @mbggenerated
     */
    public void setDeleteFlag(Byte deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

	public String getCreateTime() {
		return createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}
    
    
}