package com.yunda.inter.outsideInterface.mapper;

import com.yunda.inter.outsideInterface.bean.*;

public interface SynVehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syn_vehicle
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syn_vehicle
     *
     * @mbggenerated
     */
    int insert(SynVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syn_vehicle
     *
     * @mbggenerated
     */
    int insertSelective(SynVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syn_vehicle
     *
     * @mbggenerated
     */
    SynVehicle selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syn_vehicle
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SynVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syn_vehicle
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SynVehicle record);
    
    /**
     * 根据车牌号码查询，车辆对象数据
     */
    SynVehicle selectByCard(String card);
}