package com.yunda.gps.vehicleMaintain.pojo;

import java.util.Date;

public class VideoLine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_line.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_line.VEHICLE_MAINTAIN_ID
     *
     * @mbggenerated
     */
    private String vehicleMaintainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_line.INSTALL_LINE
     *
     * @mbggenerated
     */
    private String installLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_line.IS_INSTALL
     *
     * @mbggenerated
     */
    private Integer isInstall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_line.INSTALL_LOCATION
     *
     * @mbggenerated
     */
    private String installLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_line.INSTALL_STATUS
     *
     * @mbggenerated
     */
    private String installStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_line.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_line.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_line.CREATE_BY
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_line.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_line.UPDATE_BY
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_line.DELETE_FLAG
     *
     * @mbggenerated
     */
    private Integer deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_line.ID
     *
     * @return the value of video_line.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_line.ID
     *
     * @param id the value for video_line.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_line.VEHICLE_MAINTAIN_ID
     *
     * @return the value of video_line.VEHICLE_MAINTAIN_ID
     *
     * @mbggenerated
     */
    public String getVehicleMaintainId() {
        return vehicleMaintainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_line.VEHICLE_MAINTAIN_ID
     *
     * @param vehicleMaintainId the value for video_line.VEHICLE_MAINTAIN_ID
     *
     * @mbggenerated
     */
    public void setVehicleMaintainId(String vehicleMaintainId) {
        this.vehicleMaintainId = vehicleMaintainId == null ? null : vehicleMaintainId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_line.INSTALL_LINE
     *
     * @return the value of video_line.INSTALL_LINE
     *
     * @mbggenerated
     */
    public String getInstallLine() {
        return installLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_line.INSTALL_LINE
     *
     * @param installLine the value for video_line.INSTALL_LINE
     *
     * @mbggenerated
     */
    public void setInstallLine(String installLine) {
        this.installLine = installLine == null ? null : installLine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_line.IS_INSTALL
     *
     * @return the value of video_line.IS_INSTALL
     *
     * @mbggenerated
     */
    public Integer getIsInstall() {
        return isInstall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_line.IS_INSTALL
     *
     * @param isInstall the value for video_line.IS_INSTALL
     *
     * @mbggenerated
     */
    public void setIsInstall(Integer isInstall) {
        this.isInstall = isInstall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_line.INSTALL_LOCATION
     *
     * @return the value of video_line.INSTALL_LOCATION
     *
     * @mbggenerated
     */
    public String getInstallLocation() {
        return installLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_line.INSTALL_LOCATION
     *
     * @param installLocation the value for video_line.INSTALL_LOCATION
     *
     * @mbggenerated
     */
    public void setInstallLocation(String installLocation) {
        this.installLocation = installLocation == null ? null : installLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_line.INSTALL_STATUS
     *
     * @return the value of video_line.INSTALL_STATUS
     *
     * @mbggenerated
     */
    public String getInstallStatus() {
        return installStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_line.INSTALL_STATUS
     *
     * @param installStatus the value for video_line.INSTALL_STATUS
     *
     * @mbggenerated
     */
    public void setInstallStatus(String installStatus) {
        this.installStatus = installStatus == null ? null : installStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_line.REMARK
     *
     * @return the value of video_line.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_line.REMARK
     *
     * @param remark the value for video_line.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_line.CREATE_TIME
     *
     * @return the value of video_line.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_line.CREATE_TIME
     *
     * @param createTime the value for video_line.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_line.CREATE_BY
     *
     * @return the value of video_line.CREATE_BY
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_line.CREATE_BY
     *
     * @param createBy the value for video_line.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_line.UPDATE_TIME
     *
     * @return the value of video_line.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_line.UPDATE_TIME
     *
     * @param updateTime the value for video_line.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_line.UPDATE_BY
     *
     * @return the value of video_line.UPDATE_BY
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_line.UPDATE_BY
     *
     * @param updateBy the value for video_line.UPDATE_BY
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_line.DELETE_FLAG
     *
     * @return the value of video_line.DELETE_FLAG
     *
     * @mbggenerated
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_line.DELETE_FLAG
     *
     * @param deleteFlag the value for video_line.DELETE_FLAG
     *
     * @mbggenerated
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}