package com.yunda.gps.vehicleMaintain.mapper;

import java.util.List;

import com.yunda.gps.vehicleMaintain.pojo.VideoLine;

public interface VideoLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_line
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_line
     *
     * @mbggenerated
     */
    public void insertVideoLine(VideoLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_line
     *
     * @mbggenerated
     */
    int insertSelective(VideoLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_line
     *
     * @mbggenerated
     */
    VideoLine selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_line
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VideoLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_line
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VideoLine record);

    /**
     * 根据vehicleMaintainId新增摄像头信息
     * @return
     */
    List<VideoLine> queryByVehicleMaintainId(String id);

    void updateVideoLineByVehicleMaintainId(VideoLine videoLine);

    void deleteVideoLineByVehicleMaintainId(VideoLine videoLine);
}