package com.yunda.gps.vehicleRecord.bean;

import java.io.Serializable;
import java.util.Date;

import com.yunda.app.entity.vo.PageQueryParams;

public class VehicleRecord extends PageQueryParams implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 7022610092588457483L;
	
	/**
     * 车辆编码
     *
     * @mbggenerated
     */
    private String vehicleId;

    /**
     * 表名称
     *
     * @mbggenerated
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_record.DELETE_FLAG
     *
     * @mbggenerated
     */
    private Integer deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_record.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_record.CREATE_BY
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_record.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_record.UPDATE_BY
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_record.VEHICLE_ID
     *
     * @return the value of vehicle_record.VEHICLE_ID
     *
     * @mbggenerated
     */
    public String getVehicleId() {
        return vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_record.VEHICLE_ID
     *
     * @param vehicleId the value for vehicle_record.VEHICLE_ID
     *
     * @mbggenerated
     */
    public void setVehicleId(String vehicleId) {
        this.vehicleId = vehicleId == null ? null : vehicleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_record.TABLE_NAME
     *
     * @return the value of vehicle_record.TABLE_NAME
     *
     * @mbggenerated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_record.TABLE_NAME
     *
     * @param tableName the value for vehicle_record.TABLE_NAME
     *
     * @mbggenerated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }



    public Integer getDeleteFlag() {
		return deleteFlag;
	}

	public void setDeleteFlag(Integer deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_record.CREATE_TIME
     *
     * @return the value of vehicle_record.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_record.CREATE_TIME
     *
     * @param createTime the value for vehicle_record.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_record.CREATE_BY
     *
     * @return the value of vehicle_record.CREATE_BY
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_record.CREATE_BY
     *
     * @param createBy the value for vehicle_record.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_record.UPDATE_TIME
     *
     * @return the value of vehicle_record.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_record.UPDATE_TIME
     *
     * @param updateTime the value for vehicle_record.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_record.UPDATE_BY
     *
     * @return the value of vehicle_record.UPDATE_BY
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_record.UPDATE_BY
     *
     * @param updateBy the value for vehicle_record.UPDATE_BY
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }
}